# UFLO Console Configuration Properties

# Debug mode
uflo.debug=false

# Default task diagram info provider
uflo.disableDefaultTaskDiagramInfoProvider=false

# File process provider
uflo.defaultFileStoreDir=/WEB-INF/processfiles
uflo.disableDefaultFileProcessProvider=false

# Diagram configuration
uflo.diagram.showTime=true
uflo.diagram.passedNodeBgcolor=245,245,245
uflo.diagram.passedNodeFontColor=150,150,150
uflo.diagram.passedNodeFontSize=13
uflo.diagram.passedNodeBorderColor=180,180,180
uflo.diagram.passedConnectionColor=180,180,180
uflo.diagram.passedConnectionFontColor=180,180,180
uflo.diagram.passedConnectionFontSize=12
uflo.diagram.multiCurrentNodeBgcolor=255,255,102
uflo.diagram.multiCurrentNodeFontColor=255,102,0
uflo.diagram.multiCurrentNodeFontSize=13
uflo.diagram.multiCurrentNodeBorderColor=255,204,0
uflo.diagram.connectionColor=0,69,123
uflo.diagram.connectionFontColor=0,69,123
uflo.diagram.connectionFontSize=12
uflo.diagram.nodeBgcolor=255,255,255
uflo.diagram.nodeFontColor=0,0,0
uflo.diagram.nodeFontSize=13
uflo.diagram.nodeBorderColor=0,69,123
uflo.diagram.currentNodeBgcolor=255,255,204
uflo.diagram.currentNodeFontColor=255,102,0
uflo.diagram.currentNodeFontSize=13
uflo.diagram.currentNodeBorderColor=255,204,0